color: null
fieldLayouts:
  3ed73103-5d28-4182-a7f8-b7027493e11f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-15T17:02:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 37d17f6c-b65c-4271-a9cf-11e638dbd49f # Header Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 721a83ee-eebd-4d58-ad73-043151a0c2b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T17:02:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 990b323d-4863-4856-b363-41b157696e93 # subheader
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efef97a8-5692-4613-95a6-cc6f2426138e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T17:02:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3d96256f-b6d2-47a1-8f8c-0a10041ab9ca # plain
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eae2e46-04c4-4770-b59b-95c1dad83f9b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T17:02:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 90f177f6-9c40-4037-abc6-492335432020 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7854c531-9bb8-4acd-af87-2b983c85c084
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba821289-c864-49e4-939a-ec4d28bf5f5c
        userCondition: null
handle: textblock
hasTitleField: false
icon: null
name: textblock
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
