altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  d2e43273-023e-4827-9cab-cf76f0a6fab4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-15T17:44:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 14c6fdff-c977-483d-880c-ecb79039e216
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5f575466-6d43-40a5-8714-d1dafb1fc62b
        userCondition: null
fs: local
handle: assets
name: assets
sortOrder: 7
subpath: assets\images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
