defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 93a2f3f5-9f36-492c-8688-43f600d49e6d # pagebuilder
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cc9651ce-50af-4b13-94b6-f94d2329580f: # craft
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{slug}'
type: channel
